spring:
  application:
    name: sy-pay
  thymeleaf:
    cache: false
server:
  port: 80
  servlet:
    context-path: /rbcrm_war_exploded
wechat:
  app-id: wx133e2db02bbbf048
  secret: cefe986e0311eb653e03b3d5df8002bd
  mch-id: 1601453760
  mch-key: ZjvqngRLscbgfu9jny8IZgjHk1gCLNY1
  sub-app-id: wx1fc14fbe6d2efdc1
  sub-mch-id: 1603865805
  key-path: C:/Users/Admin/Desktop/1601453760_20201127_cert/apiclient_cert.p12
  notify-url:  http://6deb9d67594b.ngrok.io/rbcrm_war_exploded/gw/wxpay/wxPayNotifyifyUrl
  refund-notify-url:  http://6deb9d67594b.ngrok.io/rbcrm_war_exploded/gw/wxpay/wxRefundNotifyUrl


