server:
  port: 9001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    #数据源
    url: jdbc:mysql://hadoop000:3306/symall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&&allowMultiQueries=true&verifyServerCertificate=false
    username: qing
    password: qing
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: sy-hikariCP
management:
  endpoints:
    web:

      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
