###-----------------------------nacos注册中和配置中心
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
###----------------------------------------------dubbo配置
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: sy-item-mall
